vuplus: update bsp
commit 25d5352
Author: Hains van den Bosch <hainsvdbosch@ziggo.nl>
Date:   Mon Jul 8 09:05:34 2024 +0200

    webkithbbtv: Use tarball to fix fetch failure

    ERROR: enigma2-plugin-extensions-webkithbbtv-1.1-20170105.r0 do_fetch: Bitbake Fetcher Error: FetchError('Unable to fetch URL from any source.',
    'https://source.mynonpublic.com/vuplus/release/support/webkit-hbbtv-plugin_20170105.r0.tar.gz')