meta-openpli: fix python-mutagen md5 checksum failure on download
The python-mutagen recipe set SRC_URI[md5sum] using a variable which doesn't
seem to be correctly evaluated, resulting in this kind of error message
during source fetching:

ERROR: Fetcher failure for URL: <blah...>
Checksum mismatch!
File: '/home/foobar/openpli-oe-core/sources/mutagen-1.18.tar.gz' has md5
checksum 0c2cd954e4bacd79fadd45afc4acce4c when ${MD5SUM} was expected

This breaks the vuduo2 build for me.  Fix by expressing the md5sum as a
string literal where it is used.