octagon: update bsp
commit 601a7d5
Author: Betacentauri <betacentauri@arcor.de>
Date:   3 minutes ago

    Use proper location for kernel files

commit af25218
Merge: cf6cfc2 6f6229b
Author: Betacentauri <betacentauri@users.noreply.github.com>
Date:   5 minutes ago

    Merge pull request #4 from OpenPLi/zeus

    fix octagonemmc image build

commit 6f6229b
Author: Athanasios Oikonomou <athoik@gmail.com>
Date:   23 minutes ago

    fix octagonemmc image build

    This commit fixes the following issue shown after clean build on zeus branch.

    ERROR: openpli-enigma2-image-1.0-r0 do_image_octagonemmc: Execution of '/zeus/build/tmp/work/sf8008-oe-linux-gnueabi/openpli-enigma2-image/1.0-r0/temp/run.do_image_octagonemmc.16493' failed with exit code 1:
    mke2fs 1.45.3 (14-Jul-2019)
    The file /zeus/build/tmp/deploy/images/sf8008/sf8008-partitions/rootfs.ext4 does not exist and no size was specified.
    WARNING: exit code 1 from a shell command.

commit cf6cfc2
Author: zhtq <zhangtianqingzh@gmail.com>
Date:   14 hours ago

    fix streaming crash after zap channel