directfb: Provide directfb-native
Lost with last commit.
https://github.com/OpenPLi/openpli-oe-core/commit/2d733580fb6b9db62efb82f37c68c14cf697dfef

When building feed.

ERROR: Nothing PROVIDES 'directfb-native' (but virtual:native:/home/hains/test-images/openpli-oe-core/openembedded-core/
meta/recipes-graphics/cairo/cairo_1.18.0.bb DEPENDS on or otherwise requires it).