Do not copy ownership when installing files.
Exception: Exception: KeyError: 'getpwuid(): uid not found: 1000'
Path ./package/usr/share/stalker/web is owned by uid 1000, gid 1000, which doesn't match any user/group on target. This may be due to host contamination.