lcd4linux: Add recipe to install plugin.py
To fix webinterface error: Processing Failed

File "/usr/lib/enigma2/python/Plugins/Extensions/LCD4linux/WebConfigSite.py", line 70, in ParseCode
    for line in open(Py, "r").readlines():
builtins.FileNotFoundError: [Errno 2] No such file or directory: '/usr/lib/enigma2/python/Plugins/Extensions/LCD4linux/plugin.py'

We can't use plugin.pyc.

Create recipe as I can't pypass the package-split mech.
Tried FILES_append and FILES_enigma2-plugin-extensions-lcd4linux-src_remove etc.

Instead of renaming a duplicate plugin file with script or just use a duplicate plugin file with another extension, I think this is
the best solution for now.

TODO: Better solution.