enigma2: add python-importlib required fom swig
Traceback (most recent call last):
  File "/usr/lib/enigma2/python/mytest.py", line 6, in <module>
    from Tools.Profile import profile, profile_final
  File "/usr/lib/enigma2/python/Tools/Profile.py", line 3, in <module>
  File "/usr/lib/enigma2/python/Tools/Directories.py", line 5, in <module>
  File "/usr/lib/enigma2/python/enigma.py", line 21, in <module>
  File "/usr/lib/enigma2/python/enigma.py", line 14, in swig_import_helper
ImportError: No module named importlib