redsea: Use meson instead of autotools
https://github.com/windytan/redsea/commit/a48e2b2efb71e24a5ae8920cc564ece7731f0104

Fix compile error:

../git/src/redsea.cc:21:10: fatal error: build/config.h: No such file or directory
|    21 | #include "build/config.h"
|       |          ^~~~~~~~~~~~~~~~