directfb: Fix build
Triggered with new override syntax.

ERROR: Nothing PROVIDES 'sysfsutilslibgles-vuultimo4k' (but /home/hains/test-images/openpli-oe-core/meta-openembedded/meta-oe/recipes-graphics/
directfb/directfb_1.7.7.bb DEPENDS on or otherwise requires it). Close matches:
  libgles-vuultimo4k
  libvugles2-vuultimo4k
NOTE: Runtime target 'gstreamer1.0-plugins-bad-opusparse' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['gstreamer1.0-plugins-bad-opusparse', 'cairo', 'directfb', 'sysfsutilslibgles-vuultimo4k']