gigablue: update bsp
commit e615991
Merge: 826c290 737b5c8
Author: Tomas Andersson <64785901+neo-pli-bsps@users.noreply.github.com>
Date:   Thu May 4 22:33:41 2023 +0100

    Merge pull request #4 from Taapat/bluetooth

    Remove plugin bluetoothsetup-gb7252 from gb7252 image

commit 737b5c8
Author: Taapat <taapat@gmail.com>
Date:   Thu May 4 16:26:15 2023 +0300

    Remove plugin bluetoothsetup-gb7252 from gb7252 image

    In the plugin is used the closed-source c library _gbbt, which is not compatible with python3, so the plugin does not work because it calls GSOD when strating:
    ImportError: dynamic module does not define module export function (PyInit__gbbt)