kodi: Remove file-rdeps error for now
ERROR: kodi-21.0+gitr-r0 do_package_qa: QA Issue: /usr/lib/kodi/kodi-stb contained in package kodi
requires libEGL.so, but no providers found in RDEPENDS:kodi? [file-rdeps]