iptvsubparse: add missing source files
The htmlcleaner source was missing making module unusable.

This commit fixes the following error:

>>> import _subparser.so
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: ./_subparser.so: undefined symbol: strip_html_tags