transmission: Update to latest git revision
Fix error

undefined reference to symbol '__atomic_load_8@@LIBATOMIC_1.0'

https://github.com/transmission/transmission/commit/d42d0f3f3f50c01cda1d9f7180d1f4a3ef8aba63

Bump version to 4.0.6 (sync version with 4.0.x branch).