directfb: Remove gfxdriver drivers
As it breaks gstreamer1.0-plugins-base.

/home/hains/test-images/openpli-oe-core/build/tmp/work/armv7ahf-neon-oe-linux-gnueabi/gstreamer1.0-plugins-base/
1.24.5/recipe-sysroot/usr/include/EGL/eglplatform.h:128:10: fatal error: X11/Xlib.h: No such file or directory
|   128 | #include <X11/Xlib.h>
|       |          ^~~~~~~~~~~~