python2: update bsp
commit 75350866
Author: Martin Jansa <Martin.Jansa@gmail.com>
Date:   Wed Oct 27 11:29:32 2021 +0200

    python-pywbem-native: openlmi-tools: blacklist due to openssl-3

    * blacklist python-pywbem-native as well, because native python-m2crypto is blacklisted:
      ERROR: Nothing PROVIDES 'python-m2crypto-native' (but virtual:native:meta-python2/recipes-extended/pywbem/python-pywbem_0.15.0.bb DEPENDS on or otherwise requires it)
      python-m2crypto-native was skipped: Recipe is blacklisted: Not compatible with openssl-3, http://errors.yoctoproject.org/Errors/Details/614896/ SWIG/_m2crypto_wrap.c:32981:102: error: RSA_SSLV23_PADDING undeclared (first use in this function); did you mean RSA_NO_PADDING?

    * move openlmi-tools blacklist from python2-target-recipes-blacklist.inc to
      layer.conf, because python-pywbem/python-m2crypto are blacklisted even
      when python2-target-recipes-blacklist.inc isn't included in DISTRO config
      so openlmi-tools need the same to fix:

      ERROR: Nothing PROVIDES 'python-m2crypto' (but meta-openembedded/meta-oe/recipes-extended/openlmi/openlmi-tools_0.10.5.bb DEPENDS on or otherwise requires it)
      python-m2crypto was skipped: Recipe is blacklisted: Not compatible with openssl-3, http://errors.yoctoproject.org/Errors/Details/614896/ SWIG/_m2crypto_wrap.c:32981:102: error: RSA_SSLV23_PADDING undeclared (first use in this function); did you mean RSA_NO_PADDING?
      ERROR: Nothing PROVIDES 'python-pywbem' (but meta-openembedded/meta-oe/recipes-extended/openlmi/openlmi-tools_0.10.5.bb DEPENDS on or otherwise requires it)
      python-pywbem was skipped: Recipe is blacklisted: depends on python-m2crypto which fails to build with openssl-3
      ERROR: Nothing RPROVIDES 'openlmi-tools' (but meta-openembedded/meta-oe/recipes-extended/openlmi/openlmi-tools_0.10.5.bb RDEPENDS on or otherwise requires it)
      No eligible RPROVIDERs exist for 'openlmi-tools'
      NOTE: Runtime target 'openlmi-tools' is unbuildable, removing...
      Missing or unbuildable dependency chain was: ['openlmi-tools']
      ERROR: Nothing RPROVIDES 'openlmi-tools-dev' (but meta-openembedded/meta-oe/recipes-extended/openlmi/openlmi-tools_0.10.5.bb RDEPENDS on or otherwise requires it)
      No eligible RPROVIDERs exist for 'openlmi-tools-dev'
      NOTE: Runtime target 'openlmi-tools-dev' is unbuildable, removing...
      Missing or unbuildable dependency chain was: ['openlmi-tools-dev']

    Signed-off-by: Martin Jansa <Martin.Jansa@gmail.com>

commit 5578a7cf
Author: Martin Jansa <Martin.Jansa@gmail.com>
Date:   Tue Oct 26 16:09:09 2021 +0200

    python-m2crypto, python-pywbem, openlmi-tools: blacklist due to openssl-3

    * python-m2crypto fails to build with openssl-3.0:

    http://errors.yoctoproject.org/Errors/Details/614896/
    SWIG/_m2crypto_wrap.c: In function 'init_m2crypto':
    SWIG/_m2crypto_wrap.c:32981:102: error: 'RSA_SSLV23_PADDING' undeclared (first use in this function); did you mean 'RSA_NO_PADDING'?
    32981 |   SWIG_Python_SetConstant(d, d == md ? public_interface : NULL, "sslv23_padding",SWIG_From_int((int)(RSA_SSLV23_PADDING)));
          |                                                                                                      ^~~~~~~~~~~~~~~~~~
          |                                                                                                      RSA_NO_PADDING

    * python-pywbem, openlmi-tools depend on python-m2crypto

    Signed-off-by: Martin Jansa <Martin.Jansa@gmail.com>

commit c1f638ab
Author: Martin Jansa <Martin.Jansa@gmail.com>
Date:   Tue Oct 26 16:19:11 2021 +0200

    python-systemd: inherit pkgconfig

    * otherwise fails when searching for libsystemd-journal:
      http://errors.yoctoproject.org/Errors/Details/614895/

    DEBUG: Executing shell function do_configure
    Traceback (most recent call last):
      File "setup.py", line 55, in <module>
        **lib('libsystemd', 'libsystemd-journal', **defines))
      File "setup.py", line 40, in lib
        status, result = pkgconfig(name, **kw)
      File "setup.py", line 18, in pkgconfig
        status, result = call(pkgconf, '--libs', '--cflags', package)
      File "setup.py", line 8, in call
        universal_newlines=True)
      File "TOPDIR/tmp-glibc/work/core2-64-oe-linux/python-systemd/234-r0/recipe-sysroot-native/usr/lib/python2.7/subprocess.py", line 394, in __init__
        errread, errwrite)
      File "TOPDIR/tmp-glibc/work/core2-64-oe-linux/python-systemd/234-r0/recipe-sysroot-native/usr/lib/python2.7/subprocess.py", line 1047, in _execute_child
        raise child_exception
    OSError: [Errno 2] No such file or directory

    Signed-off-by: Martin Jansa <Martin.Jansa@gmail.com>

commit a8c31720
Author: Martin Jansa <Martin.Jansa@gmail.com>
Date:   Tue Oct 26 16:18:39 2021 +0200

    python-pyparted: inherit pkgconfig

    * otherwise fails when searching for libparted:
      http://errors.yoctoproject.org/Errors/Details/614897/

    DEBUG: Executing shell function do_configure
    Traceback (most recent call last):
      File "setup.py", line 60, in <module>
        check_mod_version('libparted', need_libparted_version)
      File "setup.py", line 54, in check_mod_version
        modversion = subprocess.check_output(["pkg-config", "--modversion", module]).decode('utf-8').split()[0]
      File "TOPDIR/tmp-glibc/work/core2-64-oe-linux/python-pyparted/3.11.4+gitAUTOINC+104ca13567-r0/recipe-sysroot-native/usr/lib/python2.7/subprocess.py", line 216, in check_output
        process = Popen(stdout=PIPE, *popenargs, **kwargs)
      File "TOPDIR/tmp-glibc/work/core2-64-oe-linux/python-pyparted/3.11.4+gitAUTOINC+104ca13567-r0/recipe-sysroot-native/usr/lib/python2.7/subprocess.py", line 394, in __init__
        errread, errwrite)
      File "TOPDIR/tmp-glibc/work/core2-64-oe-linux/python-pyparted/3.11.4+gitAUTOINC+104ca13567-r0/recipe-sysroot-native/usr/lib/python2.7/subprocess.py", line 1047, in _execute_child
        raise child_exception
    OSError: [Errno 2] No such file or directory

    Signed-off-by: Martin Jansa <Martin.Jansa@gmail.com>

commit 4ab3b5a6
Author: Martin Jansa <Martin.Jansa@gmail.com>
Date:   Sun Oct 17 14:20:22 2021 -0700

    python-cryptography: fix build with openssl-3

    Signed-off-by: Martin Jansa <Martin.Jansa@gmail.com>

commit 5243d509
Author: Martin Jansa <Martin.Jansa@gmail.com>
Date:   Mon Sep 20 18:11:11 2021 +0200

    python-lxml: inherit pkgconfig

    * fixes:
    | Building without Cython.
    | ERROR: /bin/sh: 1: pkg-config: not found
    |
    | ** make sure the development packages of libxml2 and libxslt are installed **
    |
    | Using build configuration of libxslt
    | running build
    | running build_py
    | running build_ext
    | building 'lxml.etree' extension
    | gcc -fno-strict-aliasing -isystem/OE/build/oe-core/tmp-glibc/work/x86_64-linux/python-lxml-native/4.4.2-r0/recipe-sysroot-native/usr/include -O2 -pipe -DNDEBUG -g -O3 -Wall -Wstrict-prototypes -isystem/OE/build/oe-core/tmp-glibc/work/x86_64-linux/python-lxml-native/4.4.2-r0/recipe-sysroot-native/usr/include -O2 -pipe -isystem/OE/build/oe-core/tmp-glibc/work/x86_64-linux/python-lxml-native/4.4.2-r0/recipe-sysroot-native/usr/include -fPIC -DCYTHON_CLINE_IN_TRACEBACK=0 -Isrc -Isrc/lxml/includes -I/OE/build/oe-core/tmp-glibc/work/x86_64-linux/python-lxml-native/4.4.2-r0/recipe-sysroot-native/usr/include/python2.7 -c src/lxml/etree.c -o build/temp.linux-x86_64-2.7/src/lxml/etree.o -w
    | In file included from src/lxml/etree.c:692:
    | src/lxml/includes/etree_defs.h:14:10: fatal error: libxml/xmlversion.h: No such file or directory
    |    14 | #include "libxml/xmlversion.h"
    |       |          ^~~~~~~~~~~~~~~~~~~~~
    | compilation terminated.
    | Compile failed: command 'gcc' failed with exit status 1
    | cc -I/usr/include/libxml2 -c /tmp/xmlXPathInithJP6pr.c -o tmp/xmlXPathInithJP6pr.o
    | unable to execute 'cc': No such file or directory
    | *********************************************************************************
    | Could not find function xmlCheckVersion in library libxml2. Is libxml2 installed?
    | *********************************************************************************
    | error: command 'gcc' failed with exit status 1

    Signed-off-by: Martin Jansa <Martin.Jansa@gmail.com>

commit f522fa70
Author: Martin Jansa <Martin.Jansa@gmail.com>
Date:   Fri Jul 30 10:18:01 2021 +0200

    layer.conf: Update to honister

    This marks the layers as compatible with honister now they use the new override
    syntax.

    Signed-off-by: Martin Jansa <Martin.Jansa@gmail.com>

commit 4626bb64
Author: Martin Jansa <Martin.Jansa@gmail.com>
Date:   Thu Jul 29 17:06:40 2021 +0200

    Convert to new override syntax

    This is the result of automated script (0.9.0) conversion:

    oe-core/scripts/contrib/convert-overrides.py .

    converting the metadata to use ":" as the override character instead of "_".

    Signed-off-by: Martin Jansa <Martin.Jansa@gmail.com>