Fix error ...
bb.data_smart.ExpansionError: Failure expanding variable GITPKGVTAG, expression was ${@get_git_pkgv(d, True)} which triggered exception FetchError: Fetcher failure: The SRCREV_FORMAT variable must be set when multiple SCMs are used