vuplus: update bsp
commit 76c2dcb
Author: Tomas Andersson <neoplibsps@gmail.com>
Date:   Fri Oct 14 21:05:07 2022 +0100

    Fixed Python3 issue in RemoteControlCode when pressing Green

    TypeError: in method 'new_ePoint', argument 1 of type 'int'

    Thanks @scriptmelvin