python2: update bsp
commit 4ab3b5a6
Author: Martin Jansa <Martin.Jansa@gmail.com>
Date:   Sun Oct 17 14:20:22 2021 -0700

    python-cryptography: fix build with openssl-3

    Signed-off-by: Martin Jansa <Martin.Jansa@gmail.com>

commit 5243d509
Author: Martin Jansa <Martin.Jansa@gmail.com>
Date:   Mon Sep 20 18:11:11 2021 +0200

    python-lxml: inherit pkgconfig

    * fixes:
    | Building without Cython.
    | ERROR: /bin/sh: 1: pkg-config: not found
    |
    | ** make sure the development packages of libxml2 and libxslt are installed **
    |
    | Using build configuration of libxslt
    | running build
    | running build_py
    | running build_ext
    | building 'lxml.etree' extension
    | gcc -fno-strict-aliasing -isystem/OE/build/oe-core/tmp-glibc/work/x86_64-linux/python-lxml-native/4.4.2-r0/recipe-sysroot-native/usr/include -O2 -pipe -DNDEBUG -g -O3 -Wall -Wstrict-prototypes -isystem/OE/build/oe-core/tmp-glibc/work/x86_64-linux/python-lxml-native/4.4.2-r0/recipe-sysroot-native/usr/include -O2 -pipe -isystem/OE/build/oe-core/tmp-glibc/work/x86_64-linux/python-lxml-native/4.4.2-r0/recipe-sysroot-native/usr/include -fPIC -DCYTHON_CLINE_IN_TRACEBACK=0 -Isrc -Isrc/lxml/includes -I/OE/build/oe-core/tmp-glibc/work/x86_64-linux/python-lxml-native/4.4.2-r0/recipe-sysroot-native/usr/include/python2.7 -c src/lxml/etree.c -o build/temp.linux-x86_64-2.7/src/lxml/etree.o -w
    | In file included from src/lxml/etree.c:692:
    | src/lxml/includes/etree_defs.h:14:10: fatal error: libxml/xmlversion.h: No such file or directory
    |    14 | #include "libxml/xmlversion.h"
    |       |          ^~~~~~~~~~~~~~~~~~~~~
    | compilation terminated.
    | Compile failed: command 'gcc' failed with exit status 1
    | cc -I/usr/include/libxml2 -c /tmp/xmlXPathInithJP6pr.c -o tmp/xmlXPathInithJP6pr.o
    | unable to execute 'cc': No such file or directory
    | *********************************************************************************
    | Could not find function xmlCheckVersion in library libxml2. Is libxml2 installed?
    | *********************************************************************************
    | error: command 'gcc' failed with exit status 1

    Signed-off-by: Martin Jansa <Martin.Jansa@gmail.com>

commit f522fa70
Author: Martin Jansa <Martin.Jansa@gmail.com>
Date:   Fri Jul 30 10:18:01 2021 +0200

    layer.conf: Update to honister

    This marks the layers as compatible with honister now they use the new override
    syntax.

    Signed-off-by: Martin Jansa <Martin.Jansa@gmail.com>

commit 4626bb64
Author: Martin Jansa <Martin.Jansa@gmail.com>
Date:   Thu Jul 29 17:06:40 2021 +0200

    Convert to new override syntax

    This is the result of automated script (0.9.0) conversion:

    oe-core/scripts/contrib/convert-overrides.py .

    converting the metadata to use ":" as the override character instead of "_".

    Signed-off-by: Martin Jansa <Martin.Jansa@gmail.com>