skins-pli-hd: Remove ConfigListSlider from parameter name
To fix:
File "/usr/lib/enigma2/python/Screens/Wizard.py", line 186, in __init__
    self["config"] = ConfigList([], session=session)
  File "/usr/lib/enigma2/python/Components/ConfigList.py", line 16, in __init__
    height, space = parameters.get("ConfigListSlider", (17, 0))
ValueError: not enough values to unpack (expected 2, got 0)

When casting the values to a list or tuple, the resolution is wrong( everything is
4 times so big).

Instead of changing vaulues, remove it for now.
Needs review.