kodi: Restore INSANE_SKIP
ERROR: kodi-19.4+gitrAUTOINC+aac12f6fc4-r0 do_package_qa: QA Issue: /usr/lib/kodi/kodi-stb contained
in package kodi requires libmali.so, but no providers found in RDEPENDS_kodi? [file-rdeps]

etc.