xsarius: update bsp
commit dee7149
Merge: 580a68e 9d2c690
Author: pli3 <kamase79@daum.net>
Date:   Wed Oct 19 18:47:11 2016 +0900

    Merge pull request #3 from athoik/pli5

    Set KERNEL_OUTPUT_DIR variable

commit 9d2c690
Author: Athanasios Oikonomou <athoik@gmail.com>
Date:   Sun Sep 25 19:34:18 2016 +0300

    remove inherit autotools instead of adding an empty do_compile

commit 2f095c3
Author: Athanasios Oikonomou <athoik@gmail.com>
Date:   Mon Sep 12 23:22:45 2016 +0300

    xsarius-shutdown: add empty do_compile

    In order to avoid the following error:

    ERROR: oe_runmake failed
    make: *** No targets specified and no makefile found.  Stop.

commit 344c9bb
Author: Athanasios Oikonomou <athoik@gmail.com>
Date:   Mon Sep 12 23:11:42 2016 +0300

    Set KERNEL_OUTPUT_DIR variable

    KERNEL_OUTPUT_DIR defaults to arch/${ARCH}/boot, which isn't where
    these kernels end up. Previously this was done with KERNEL_OUTPUT,
    but now that the kernel class supports multiple recipes, setting
    KERNEL_OUTPUT_DIR to "./" fixes the kernel recipes no longer
    building.