gstreamer1.0-plugins-base: Add libGLESv2.so to RDEPENDS
Fix:

ERROR: gstreamer1.0-plugins-base-1.24.5-r0 do_package_qa: QA Issue: /usr/lib/libgstgl-1.0.so.0.2405.0
contained in package libgstgl-1.0 requires libGLESv2.so, but no providers found in RDEPENDS:libgstgl-1.0? [file-rdeps]