Revert "blindscan-s2: Update git URL (#352)"
It seems that it causes problems.

bb.data_smart.ExpansionError: Failure expanding variable GITPKGV, expression was ${@get_git_pkgv(d, False)} which triggered exception ParameterError: URL: 'https://bitbucket.org/majortom/blindscan-s2.git;protocol=git' has invalid parameters. Invalid protocol - if you wish to fetch from a git repository using http, you need to instead use the git:// prefix with protocol=http

This reverts commit 370d271cfd86ee480602d15295aafe2ca268a0e8.