kodi_18: remove zgemma h10se
the BSP does not provide the drivers:

ERROR: Nothing PROVIDES 'virtual/egl'

Signed-off-by: Andrea Adami <andrea.adami@gmail.com>